# -*- coding: utf-8 -*-
"""Customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zknnMiDEBZYdwpazz3OsjvAu_ys2TLPb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# datacus=pd.read_csv("customer.csv")
# datacus.head(5)

#EDA
# datacus.describe()
# datacus.info()
# datacus.dtypes
# datacus.isnull().sum()*100/len(datacus)
# datacus.isnull().sum()
# datacus.columns

#No Duplicates
# datacus.duplicated().sum()
# datacus["email"].duplicated().sum()

#dropping columns as because it exceeds more than 30%
# datacus=datacus.drop(columns=["company","fax"])

# #replacing blank records into null

# datacus["support_rep_id"].unique()
# datacus=datacus.replace(r'^/s*$',np.nan,regex=True)

## datacus=datacus.replace([r'^/s*$',"nan","null"],np.nan,regex=True)

#filling state,postal_code,phone_number

# datacus["state"]=datacus["state"].fillna(datacus["state"].mode()[0])
# datacus["postal_code"]=datacus["postal_code"].fillna("Unknown")
# datacus["phone"]=datacus["phone"].fillna("Not Available")


# #handling null values
# datacus=datacus.dropna(subset=["",""])#aldready checked using isnull()
# #filling null based on detecting outliers#since no null in numerical data
#so dont need outlier detection
# datacus.loc[datacus[""]<0,""]=np.nan

# positive=datacus[datacus[""]<0]
# Q1=positive[""].qunatile(0.25)
# Q3=positive[""].qunatile(0.75)
# IQR=Q3-Q1
# LOWER=Q1-1.5*IQR
# UPPER=Q3+1.5*IQR
# outliers=positive[(positive[""]<LOWER)|(positive[""]>UPPER)]
# print(outliers)

# #conditional formating
# datacus["flags"]=np.where(datacus[""]<0,"","")


# #for evaluating particular numerical column
# datacus[""]=datacus[""].replace(r'[^0-9.]',"",regex=True)
# datacus[""]=pd.to_numeric(datacus[""],errors="coerce")

datacus.head(10)
datacus["full_name"].unique()
datacus=datacus.drop(columns=["first_name","last_name"])
datacus["full_name"] = (
    datacus["first_name"].fillna("") + " " + datacus["last_name"].fillna("")
).str.strip()

datacus.columns

datacus["postal_code"].unique()

datacus

datacus.to_csv("customers.csv")

dataemp=pd.read_csv("employee.csv")
dataemp.head(10)

dataemp.info()

# dataemp.isnull().sum()*100/len(dataemp)
dataemp.isnull().sum()
# dataemp.dtypes

# dataemp[dataemp["reports_to"]<=0].shape
# dataemp["hire_date"].unique()#no neg val and no text formating needed
#change dtype for birthdate,hire_date
# dataemp["birthdate"]=pd.to_datetime(dataemp["birthdate"],format="mixed",errors="coerce")
# dataemp["hire_date"]=pd.to_datetime(dataemp["hire_date"],format="mixed",errors="coerce")

# dataemp=dataemp.replace(r'^s/*$',np.nan,regex=True)

dataemp.columns

dataemp["reports_to"].unique()
# dataemp["reports_to"]=dataemp["reports_to"].fillna("No manager")
# dataemp["manager_status"] = dataemp["reports_to"].isna().map({
#     True: "No Manager",
#     False: "Has Manager"
# })

dataemp[dataemp["manager_status"]=="No Manager"].shape

# dataemp.duplicated().sum()
dataemp['email'].duplicated().sum()

dataemp.columns

dataemp=dataemp.apply(lambda x:x.str.strip()if x.dtype=="object" else x)
# dataemp = dataemp.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

dataemp["full_name"] = (
    dataemp["first_name"].fillna("") + " " + dataemp["last_name"].fillna("")
).str.strip()

# dataemp=dataemp.drop(columns=["first_name","last_name"])
dataemp.to_csv("Employees.csv")

datainv=pd.read_csv("invoice.csv")
datainv.head(10)



datainv.columns

# datainv.info()
datainv.isnull().sum()
# datainv.isnull().sum()*100/len(datainv)
# datainv.dtypes

#change dtype for invoice date
# datainv["invoice_date"]=pd.to_datetime(datainv["invoice_date"],format="mixed",errors="coerce")
# datainv["billing_state"].unique()
# print(datainv["billing_state"].mode()[0])
# datainv=datainv.replace(r'^s/*$',np.nan,regex=True)

#filling postalcode null
# datainv["billing_postal_code"]=datainv["billing_postal_code"].fillna("Unknown")

datainv["billing_state_filled"] = datainv["billing_state"].fillna("Unknown")

datainv

datainv.duplicated().sum()

# datainv["invoice_id"].duplicated().sum()


# datainv
datainv=datainv.apply(lambda x:x.str.strip()if x.dtype=="object" else x)

datainv
datainv.isnull().sum()

datainv.to_csv("Invoice.csv")

dataalm=pd.read_csv("album.csv")
dataalm

#EDA
# dataalm.describe()
# dataalm.info()
#NO NULL VALUES
# dataalm.isnull().sum()*100/len(dataalm)
# dataalm.isnull().sum()
# dataalm.dtypes
# dataalm["artist_id"].unique()
# dataalm=dataalm.replace(r'^/s*$',np.nan,regex=True)
#checking duplicates
# dataalm.duplicated().sum()
# dataalm["album_id"].duplicated().sum()
dataalm=dataalm.apply(lambda x:x.str.strip()if x.dtype=="object" else x)

dataalm.to_csv("Album.csv")

dataart=pd.read_csv("artist.csv")
dataart

#EDA
# dataart.info()
# dataart.isnull().sum()
# dataart.dtypes
# dataart["name"].unique()
# dataart=dataart.replace(r'^s/*$',np.nan,regex=True)
# dataart.duplicated().sum()
dataart["artist_id"].duplicated().sum()

dataart.to_csv("Artist.csv")

datag=pd.read_csv("genre.csv")
datag

# datag.info()
datag.isnull().sum()
# datag.dtypes
# datag["name"].unique()
# datag=datag.replace(r'^s/*$',np.nan,regex=True)
# datag.duplicated().sum()
# datag["genre_id"].duplicated().sum()

datag.to_csv("Genre.csv")

datainvo=pd.read_csv("invoice_line.csv")
datainvo

# datainvo.info()
#No null values
# datainvo.isnull().sum()
# datainvo.dtypes
# datainvo[datainvo["quantity"]<=0].shape
# datainvo["quantity"].unique()
# datainvo=datainvo.replace(r'^s/*$',np.nan,regex=True)
#duplicate
# datainvo.duplicated().sum()
# datainvo["invoice_line_id"].duplicated().sum()

datainvo.columns

datainvo.to_csv("Invoice_Line.csv")

datam=pd.read_csv("media_type.csv")
datam

# datam.info()
# datam.isnull().sum()
# datam.dtypes
# datam["name"].unique()
# datam=datam.replace(r'^/s*$',np.nan,regex=True)
# datam.duplicated().sum()
datam["media_type_id"].duplicated().sum()

datap=pd.read_csv("playlist.csv")
datap

# datap.info()
# datap.isnull().sum()
# datap.dtypes
# datap["playlist_id"].unique()
# datap=datap.replace(r'^/s*$',np.nan,regex=True)
# datap.duplicated().sum()
datap["playlist_id"].duplicated().sum()

datapt=pd.read_csv("playlist_track.csv")
datapt

# datapt.info()
# datapt.isnull().sum()
# datapt.dtypes
# datapt["track_id"].unique()
# datapt=datapt.replace(r'^/s*$',np.nan,regex=True)
# datapt.duplicated().sum()
# datapt["track_id"].duplicated().sum()

dataptt=pd.read_csv("track.csv")
dataptt

# dataptt.info()
# dataptt.isnull().sum()
# dataptt.isnull().sum()*100/len(dataptt)
# dataptt["composer"]=dataptt["composer"].fillna("Unknown")
# dataptt.dtypes
# dataptt["unit_price"].unique()
# dataptt=dataptt.replace(r'^/s*$',np.nan,regex=True)
# dataptt.duplicated().sum()
# dataptt["track_id"].duplicated().sum()

dataptt.columns

dataptt.to_csv("Track.csv")